### ISSUE TITLE
DLIS спецификация?

### ISSUE THREAD

**Issue by paceholder** [renat-b/DLIS#4]
Привет!

Не подскажите, где можно найти описание форматов (спецификацию) LIS/DLIS?

Спасибо

Дмитрий

**Comment by paceholder** [comment]
http://w3.energistics.org/rp66/v1/Toc/main.html

Кажется это оно?

**Comment by renat-b** [comment]
Привет!Да все верно! 26.07.2018, 23:31, "paceholder" <notifications@github.com>:http://w3.energistics.org/rp66/v1/Toc/main.htmlКажется это оно?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.  -- С уважением Ренат
